# Generated by Django 5.2.1 on 2025-06-02 19:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='estatus1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='movimiento',
            field=models.CharField(max_length=150),
        ),
    ]
