# Generated by Django 5.2.1 on 2025-06-10 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='id_profile',
        ),
        migrations.AddField(
            model_name='tasks',
            name='profile_id',
            field=models.ForeignKey(db_column='profile_id', default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
