# Generated by Django 5.2.1 on 2025-06-11 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_bitacora_user_profile_user'),
        ('tasks', '0002_remove_tasks_id_profile_tasks_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='profile_id',
            field=models.ForeignKey(db_column='profile_id', default=False, on_delete=django.db.models.deletion.CASCADE, to='dashboard.profile'),
        ),
    ]
